### ISSUE TITLE
Additional features prior to math.js integration

### ISSUE THREAD

**Issue by AlwinHughes** [infusion/Quaternion.js#1]
This is a continuation of this: https://github.com/josdejong/mathjs/pull/794

I think how many extra functions that are included will depend on how centered @infusion wants to keep the library on the 3D application of quaternions. 

The features that I previously added in the PR that could be worth implementing are: 

- various rounding functions 
- powers (real and quaternion) 
-  exponential 
- natural logarithm 
- creation of quaternions from a modulus, argument and unit vector (and the other way around)
- conversion of quaternions to matrix form. (different to converting a quart to a rotation matrix) 
- conversion of matrices to quaternions 

One thing I was confused about is on the current `toMatrix()` and `toMatrix4()` methods in quaternion.js would it not make more sense for them to returns 2d arrays?

**Comment by infusion** [comment]
Thanks for the list!

It would make sense to format the matrix as an actual 2d array, but the intention was to use it with CSS3 "transform: matrix3d(n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n)". See example folder - where a div is transformed to appear always leveled on your mobile device.

**Comment by infusion** [comment]
@AlwinHughes @josdejong,

- I won't add rounding functions, let's add them to math.js if needed
- pow(w,x,y,z) and pow(r) is implemented
- exp() is implemented, proven & tested
- log() is implemented, proven & tested
- have never seen modulus, argument and unit vector input. could you give an example pls?
- what do u mean with matrix form? an 4x1 matrix? there is toVector()
- rotation matrix input is pending
- documentation was extended 
- toMatrix() and toMatrix4() got optional parameters to retrieve 2d arrays.
- Quaternion.EPSILON was added in conformance to math.js API requirements

all changes are in the dev branch :)

**Comment by infusion** [comment]
We decided to not integrate Quaternion.js into math.js, as it would be too niche in a general purpose library like math.js. Quaternions have huge utility in the 3D graphics world but for studying the algebraic structure one can directly use the library without math.js. @josdejong

**Comment by josdejong** [comment]
👍 

A plugin that you can load into mathjs would be interesting though I think.
