### ISSUE TITLE
Add Typescript types

### ISSUE THREAD

**Issue by yannbriancon** [infusion/Quaternion.js#10]
Hi Robert,

I created a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60800) in DefinitelyTyped to create the Typescript types for the library.

Feel free to review it!

**Comment by infusion** [comment]
Thanks! For Fraction.js and Complex.js there is already a typing file shipped. If you want, you can also send a PR to ship it native with Quaternion.js also

**Comment by yannbriancon** [comment]
I merged in DefinitelyTyped for version 1.3.

I will add the types here for the next version with fromMatrix.
