### ISSUE TITLE
fromEuler RPY to toEuler is broken

### ISSUE THREAD

**Issue by MitchellMonaghan** [infusion/Quaternion.js#15]
If you create a Quaternion using fromEuler then use toEuler to get the inputs back out it returns completely different values. I tried to do this with a simple 45 degree pitch and received values for all 3 yaw roll pitch

**Comment by MitchellMonaghan** [comment]
Sorry I actually made a error. It's not that the RPY is broken, its actually just the typescript definition for toEuler.
Typescript says the function definition is 
```ts
(property) Quaternion.toEuler: () => {
    roll: number;
    pitch: number;
    yaw: number;
}
```

While the documentation says the function definition is Object toEuler(order="ZXY")

So I was not comparing the quaternions correctly. I would still conside the ts definition a issue to be fixed though.

**Comment by infusion** [comment]
Funny. Did you look into the `toEuler()` method because this change was made? I just published the extension to allow different axis orders yesterday. I'll fix the TS definition, thanks!

**Comment by MitchellMonaghan** [comment]
Hmm actually it seems to work sometimes and sometimes not. I'm not sure where the exact issue is but if you done something like this it doesn't do what I would expect either. Here's a website for visually seeing rotation https://compsci290-s2016.github.io/CoursePage/Materials/EulerAnglesViz/

```ts
import Quaternion from 'quaternion'
import configureMeasurements, { angle } from 'convert-units'

const convert = configureMeasurements({ angle })

const test = Quaternion.fromEuler(
      convert(10).from('deg').to('rad'),
      convert(20).from('deg').to('rad'),
      convert(30).from('deg').to('rad')
    ).toEuler()
    console.log({
      yaw: convert(test.yaw).from('rad').to('deg'),
      roll: convert(test.roll).from('rad').to('deg'),
      pitch: convert(test.pitch).from('rad').to('deg')
    })
    // Logged output in degrees
    // {yaw: 21.170229433078788, roll: 22.79587725885847, pitch: 28.024320673604695}
```
![Screenshot 2023-07-18 125900](https://github.com/infusion/Quaternion.js/assets/19611592/813e2d5f-5641-47f5-a20f-45eeab0ed251)

**Comment by bobpaul** [comment]
Huh. Using `quaternion@1.4.2`

So  yeah, if consumed as YPR, all seems fine.
```
> quat = require('quaternion')
> function toDeg(r){ return r*(180/Math.PI) }
> function toRad(d){ return d*(Math.PI/180) }
> q=quat.Quaternion.fromEuler(toRad(30), toRad(20), toRad(10), "YPR").toEuler("YPR"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)});
{ yaw: 29.999999999999993, roll: 10, pitch: 19.999999999999996 }
> q=quat.Quaternion.fromEuler(toRad(10), toRad(20), toRad(30), "YPR").toEuler("YPR"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)});
{ yaw: 10, roll: 29.999999999999993, pitch: 19.999999999999996 }
> q=quat.Quaternion.fromEuler(toRad(30), toRad(10), toRad(20), "YPR").toEuler("YPR"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)});
{ yaw: 29.999999999999996, roll: 20, pitch: 9.999999999999998 }
```
looks good here.

But consumed as "RPY"
```
> q=quat.Quaternion.fromEuler(toRad(10), toRad(20), toRad(30), "RPY").toEuler("RPY"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)})
{
  yaw: 33.75369500293538,
  roll: 19.008263264952667,
  pitch: 11.822130763866337
}
// expected yaw 30, roll 10, pitch 20

> q=quat.Quaternion.fromEuler(toRad(30), toRad(20), toRad(10), "RPY").toEuler("RPY"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)})
{
  yaw: 19.008263264952667,
  roll: 33.75369500293538,
  pitch: 11.822130763866337
}
// expected yaw 10, roll 30, pitch 20

> q=quat.Quaternion.fromEuler(toRad(10), toRad(30), toRad(20), "RPY").toEuler("RPY"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)})
{
  yaw: 27.209848583238788,
  roll: 21.245653717522035,
  pitch: 23.78571179269628
}
// expected yaw 20, roll 10, pitch 30

> q=quat.Quaternion.fromEuler(toRad(20), toRad(10), toRad(30), "RPY").toEuler("RPY"); console.log({yaw: toDeg(q.yaw), roll: toDeg(q.roll), pitch: toDeg(q.pitch)})
{
  yaw: 31.433632085496733,
  roll: 22.206930024255094,
  pitch: -1.7016819838090684
}
// expected yaw 30, roll 10, pitch 10
```
things can get quite a bit off.

**Comment by infusion** [comment]
Thanks for your time on testing these! I need to investigate on the deviation

**Comment by infusion** [comment]
I think RPY is not "broken", it is assumed to have a right-hand coordinate system, which is synonym to XYZ. I added a comment for that in the source. The visualization you provide is RPY in a a left-hand coordinate system, which is ZXY. Could you give this a try please?

**Comment by MitchellMonaghan** [comment]
I don't know what that means. We swapped to using threejs quaternion implementation and it worked as expected.

**Comment by infusion** [comment]
In the latest Quaternion.js the issue was resolved about the misleading RPY definition. BTW: Three.js does not have the RPY flag at all, right?
