### ISSUE TITLE
[book typo] Quaternion dot product not scalar?

### ISSUE THREAD

**Issue by BrainCrumbz** [infusion/Quaternion.js#17]
Hi

thanks for the great read at https://raw.org/book/algebra/quaternions/. The issue is related to that page, not to the JS library, so not sure if it's ok to raise the issue here. In case, please do share if there's a more *appropriate* place where to notify about the book.

In *Quaternion Dot Product* chapter, the operator "signature" so to say is shown as:

⋅:H×H↦H

But, being a scalar product, shouldn't the output be in R? And thus:

⋅:H×H↦R

Thanks

**Comment by infusion** [comment]
Oh! That is a very good finding, thanks a lot for that! And yes it's okay to file that issue here. Fixed it.
