### ISSUE TITLE
Exponent calculation for quaternions appears to be missing

### ISSUE THREAD

**Issue by ghost** [infusion/Quaternion.js#3]
When interpreting a quaternion as a relative rotation (and not an orientation), you could e.g. want to apply only half or only 30% of a rotation. The computation of this appears to be commonly notated with q as base and e.g. 0.5 or 0.3 as exponent: q ** 0.3 (as described here: https://math.stackexchange.com/questions/162863/how-to-get-a-part-of-a-quaternion-e-g-get-half-of-the-rotation-of-a-quaternion/162892#162892 )

However, this concept of an exponentiation of a quaternion (with the quaternion as a base and a float as an exponent) seems to be missing from Quaternion.js. There is an `exp` function, but it doesn't have any parameter for the exponent as I would have expected it.

Is there any chance this could be added?

EDIT: sorry, I missed the `pow` function. Closing this ticket, my mistake :smile:

**Comment by infusion** [comment]
Ups, seems I missed to add it to the readme.

**Comment by infusion** [comment]
Fixed, sorry for that.
