### ISSUE TITLE
Problem with toString()?

### ISSUE THREAD

**Issue by lucas-bremond** [infusion/Quaternion.js#4]
I obtain the following behavior:

```js
const q = new Quaternion(0.0, 0.0, 0.0, 1.0);
const str = q.toString(); // "k"
```

Is this expected?

**Comment by infusion** [comment]
Yes, this looks good. All components but "k" is zero. The result is `a+bi+cj+dk` and since a=b=c=0 and d=1, only `k` remains

**Comment by lucas-bremond** [comment]
I see, makes sense. Thank you!

IMHO, an option to output a more "standard" form would be interesting as well.

By standard, I mean something like: `[w, x, y, z]`, which can be used in Matlab for example.

**Comment by infusion** [comment]
hmm, I think you can use something like the following yourself then:
```
foo = "[" + new Quaternion(...).toVector().join(", ") + "]"
```
The different interpretations and notations of quaternions and also complex numbers makes it hard to come up with a general library. While the libraries (complex.js and quaternion.js) can parse any format, it's my personal sense of taste to generate the algebraic expression with the standard `toString` method. But I think that it's fine, especially when other formats can be created with a one-liner like stated above.
