### ISSUE TITLE
Adding a .toEuler() function

### ISSUE THREAD

**Issue by balzss** [infusion/Quaternion.js#5]
Being able to convert to Euler angles (and not just from) would be very nice IMO. Let me know what you think and if you agree I'm happy to implement it and submit a PR.

**Comment by infusion** [comment]
I'd love to see that PR! Would you standardize the output to a certain order like ZXY or would you implement all orders?

**Comment by balzss** [comment]
I was thinking about doing it the same way as `.fromEuler()` where there's an order parameter that defaults to 'ZXY'

**Comment by infusion** [comment]
Awesome! I look forward to review your contribution :)

**Comment by retroj** [comment]
bump :-)

**Comment by infusion** [comment]
The simplest `toEuler` implementation is now in 1.3.0. Other axis orders can follow when required.
