### ISSUE TITLE
Create Quaternion from rotation matrix

### ISSUE THREAD

**Issue by yannbriancon** [infusion/Quaternion.js#8]
Hello !

Thanks for this great minified library.

Is there a way to create a Quaternion from a matrix as the opposite of fromMatrix?

**Comment by infusion** [comment]
Hi,

I just pushed a first take on a `fromMatrix` method. It's not yet published on npm, it would be great if you could test it as well.

Robert

**Comment by yannbriancon** [comment]
Thanks Robert.

I will do a PR with new tests for the method.
